name: Send GET request to RENDER_URL

on:
  schedule:
    - cron: "*/14 9-23 * * *"  # 9:00-23:59 JST
    - cron: "*/14 0-2 * * *"   # 00:00-02:59 JST
  workflow_dispatch:  # 手動トリガーの追加

jobs:
  send_request:
    runs-on: ubuntu-latest
    environment: FOR_RENDER  # 使用するEnvironmentを指定

    steps:
      - name: Send GET request
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
        run: |
          curl -X GET "$RENDER_URL"
