name: Send HEAD request to RENDER_URL

on:
  push:
    branches:
      - main # https://blog.cohu.dev/github-actions-cron-not-working/
  schedule: # https://qiita.com/tommy_aka_jps/items/5f4fe384008ffc9fa794
  - cron: "*/3 0-14 * * *" # 9:00-23:59 JSTの間、3分毎に実行（TZについては：https://zenn.dev/blancpanda/articles/github-actions-cron-timezone-jst）
  - cron: "*/3 15-17 * * *" # 00:00-02:59 JSTの間、3分毎に実行
  workflow_dispatch: # 手動トリガーの追加

jobs:
  send_request:
    runs-on: ubuntu-latest
    environment: FOR_RENDER # 使用するEnvironmentを指定

    steps:
      - name: Send HEAD request
        env:
          RENDER_URL: ${{ secrets.RENDER_URL }}
        run: |
          curl -X HEAD "$RENDER_URL" --max-time 5 --connect-timeout 3
